// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ConceptDownloader.Models;
//
//    var fShareCloneFileRequest = FShareCloneFileRequest.FromJson(jsonString);

namespace ConceptDownloader.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class FShareCloneFileRequest
    {
        [JsonProperty("linkcode")]
        public string Linkcode { get; set; }

        [JsonProperty("clone_to_folder")]
        public string CloneToFolder { get; set; }

        [JsonProperty("secure")]
        public bool Secure { get; set; }
    }

    public partial class FShareCloneFileRequest
    {
        public static FShareCloneFileRequest FromJson(string json) => JsonConvert.DeserializeObject<FShareCloneFileRequest>(json, ConceptDownloader.Models.FShareCloneFileRequestConverter.Settings);
    }

    public static class FShareCloneFileRequestSerialize
    {
        public static string ToJson(this FShareCloneFileRequest self) => JsonConvert.SerializeObject(self, ConceptDownloader.Models.FShareCloneFileRequestConverter.Settings);
    }

    internal static class FShareCloneFileRequestConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
